# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2475e386b76f0d091ec286e85eb23528c3164f0ac8852a56eb27fde5028ea932c69baa159e997d490aa7f8f187fde9fd14a797c09dacb86f8f0a20db04cda1d6

test:
  secret_key_base: 6a3d9ad57d0583cfe7a598cf836fd09ae57cc69fbd25216b7680d7f2a8c1be9fd5c4783c18dc4c5ea85e694da928eda34ecc365bbdf1f32b656df4df5306ffda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
